runtime: go112
service: default
handlers:
  - url: /static
    static_dir: static
    secure: always
  - url: /.*
    script: auto
    secure: always
automatic_scaling:
  max_concurrent_requests: 40
  min_idle_instances: 0
  max_idle_instances: 1
  max_pending_latency: automatic
  min_pending_latency: 3000ms
env_variables:
  PROJECT_ID: "test-project"
  REDIS_ADDR: ""
  REDIS_PASS: ""
